<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;

class TextWidget extends Model
{
    use HasFactory;
    protected $fillable = [
        'key',
        'title',
        'image',
        'content',
        'active'
    ];
    //more optimized solution using cache generated by chatgpt, initial code is commented below this

    public static function getTitle(string $key)
    {
        $cacheKey = 'text-widget-' . md5($key);
        $widget = Cache::get($cacheKey, function () use ($key) {
            return TextWidget::where('key', '=', $key)
                ->where('active', '=', 1)
                ->first();
        });

        if ($widget) {
            return $widget->title;
        }

        return '';
    }

    public static function getContent(string $key)
    {
        $cacheKey = 'text-widget-' . md5($key);
        $widget = Cache::get($cacheKey, function () use ($key) {
            return TextWidget::where('key', '=', $key)
                ->where('active', '=', 1)
                ->first();
        });

        if ($widget) {
            return $widget->content;
        }

        return '';

        //     $widget = Cache::get('text-widget-' .$key, function() use($key){
        //         return TextWidget::where('key', '=', $key)
        //         ->where('active', '=', 1)
        //         ->first();
        //     });
        //     $widget= TextWidget::where('key', '=', $key)
        //     ->where('active', '=', 1)
        //     ->first();
        //     if($widget){
        //         return $widget->title;
        //     }
        //     return '';

        // }
        // public static function getContent(string $key)
        // {
        //     $widget =Cache::get('text-widget-' .$key, function() use($key){
        //         return TextWidget::where('key', '=', $key)
        //         ->where('active', '=', 1)
        //         ->first();
        //     });

        //     if($widget){
        //         return $widget->content;
        //     }
        //     return '';

    }
}
